# Generated by Django 3.1.3 on 2020-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0002_ledgbookmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgbookmain',
            name='add_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='change_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='cur_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='invst_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='prv_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='qtr_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='trgt_add_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='trgt_change_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='trgt_cur_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgbookmain',
            name='trgt_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
