# Generated by Django 3.1.3 on 2020-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0003_auto_20201115_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgbookmain',
            name='finished_yn',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
