# Generated by Django 3.1.3 on 2020-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0004_ledgbookmain_finished_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgbookmain',
            name='achievementRate',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
