# Generated by Django 3.1.3 on 2020-11-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0005_ledgbookmain_achievementrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgbookmain',
            old_name='achievementRate',
            new_name='achievement_rate',
        ),
    ]
