# Generated by Django 3.1.3 on 2020-12-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0006_auto_20201128_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgbookmain',
            old_name='user_id',
            new_name='user',
        ),
    ]
