# Generated by Django 3.1.3 on 2020-12-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0008_personalsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalsetting',
            old_name='settingAddDeposit',
            new_name='setting_add_deposit',
        ),
        migrations.RenameField(
            model_name='personalsetting',
            old_name='settingChangeRate',
            new_name='setting_change_rate',
        ),
    ]
