# Generated by Django 3.1.3 on 2021-01-08 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledgbook', '0010_stockcathe_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.CharField(max_length=6)),
                ('stock_price', models.CharField(blank=True, max_length=50)),
                ('stock_month_date', models.CharField(max_length=30)),
                ('stock_per', models.CharField(max_length=30)),
                ('stock_suspct_per', models.CharField(max_length=30)),
                ('stock_updt', models.DateTimeField(blank=True, null=True)),
                ('last_updt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stockcathe',
            name='cathe_num',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='stock_keyword',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockcathe',
            name='stock_num',
            field=models.CharField(default='000', max_length=6),
        ),
        migrations.CreateModel(
            name='StockCatheCd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathe_name', models.CharField(max_length=20)),
                ('cathe_num', models.CharField(max_length=18)),
                ('cathe_keyword', models.CharField(blank=True, max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
