# Generated by Django 3.1.3 on 2021-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0011_auto_20210108_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdailyinfo',
            name='stock_updt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
