# Generated by Django 3.1.3 on 2021-01-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0012_auto_20210108_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdailyinfo',
            name='stock_name',
            field=models.CharField(default='---', max_length=18),
        ),
    ]
