# Generated by Django 3.1.3 on 2021-01-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0013_stockdailyinfo_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='stock_keyword',
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='closing_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='hompage_addr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='listing_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='location_addr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='staple_item',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='stock_owner',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='stock_sectors',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
