# Generated by Django 3.1.3 on 2021-01-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0015_auto_20210110_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcathecd',
            name='use_yn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='sync_yn',
            field=models.CharField(default='0', max_length=10000),
        ),
        migrations.AlterField(
            model_name='stockcathecd',
            name='cathe_keyword',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
