# Generated by Django 3.1.3 on 2021-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0017_auto_20210111_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcathe',
            name='stock_num',
        ),
        migrations.RemoveField(
            model_name='stockcathecd',
            name='cathe_keyword',
        ),
        migrations.RemoveField(
            model_name='stockcathecd',
            name='cathe_name',
        ),
        migrations.RemoveField(
            model_name='stockcathecd',
            name='use_yn',
        ),
        migrations.AddField(
            model_name='stockcathe',
            name='cathe_keyword',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockcathe',
            name='cathe_name',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AddField(
            model_name='stockcathe',
            name='use_yn',
            field=models.CharField(blank=True, default='Y', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stockcathecd',
            name='stock_num',
            field=models.CharField(default='000', max_length=6),
        ),
        migrations.AlterField(
            model_name='stockcathe',
            name='cathe_num',
            field=models.CharField(default='---', max_length=18),
        ),
        migrations.AlterField(
            model_name='stockcathecd',
            name='cathe_num',
            field=models.CharField(default='000', max_length=18),
        ),
    ]
