# Generated by Django 3.1.3 on 2021-01-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0018_auto_20210111_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='sync_yn',
        ),
        migrations.AddField(
            model_name='personalsetting',
            name='sync_pos_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalsetting',
            name='user_auth_grade',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='personalsetting',
            name='user_mac_addr',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='stockcathecd',
            name='description',
            field=models.CharField(default='000', max_length=6),
        ),
        migrations.AddField(
            model_name='stockcathecd',
            name='sync_yn',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='sync_cnt',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
