# Generated by Django 3.1.3 on 2021-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgbook', '0020_auto_20210323_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcathecd',
            name='stock_name',
            field=models.CharField(default='---', max_length=18),
        ),
    ]
